apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-deployment-c80c7257
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.19.9
          name: app-container
          ports:
            - containerPort: 80
